### ISSUE TITLE
Avoid use of `shaderc` in released crate

### ISSUE THREAD

**Issue by Friz64** [fintelia/smaa-rs#2]
The crate should provide precompiled versions of every permutation (4 `ShaderQuality` * 7 `ShaderStage` = 28 permutations) of the shaders and include them. This avoids the dependency of shaderc and its inclusion in binaries.

**Comment by fintelia** [comment]
(Sorry I missed this issue... I had GitHub notifications disabled on this repo for some reason)

The crate now works with naga so it doesn't have to depend on shaderc at all :tada:
