### ISSUE TITLE
Shader error

### ISSUE THREAD

**Issue by dajmitonapake** [fintelia/smaa-rs#7]
I use wgpu 0.14.2 and smaa 0.8.0

```smaa.shader.edge_detect.vert(260,5-42): error X3017: 'SMAAEdgeDetectionVS': cannot convert from 'float4[3]' to 'float4''```

**Comment by fintelia** [comment]
That's weird, I don't observe any compilation errors with wgpu 0.14.2. Does it happen when you run the tests in this repository, or only within your own application? Some other things to compare:
* Are you using naga 0.10.0, or is it getting patched somehow?
* Do you enable any optional feature flags of naga or wgpu?

**Comment by dajmitonapake** [comment]
I'm writting a game engine and I'm trying to add smaa. With cargo.toml which looks like this: 
```
wgpu = {version = "0.14.2", features = ["glsl"]}
naga = "0.10.0"
``` 
it doesnt work like before. Could this shader not work on older graphics cards?
I have AMD Radeon HD6300m and that can be a problem

*sorry for my bad english*

**Comment by fintelia** [comment]
So, I looked into this a bit. I believe that "error X3017" is actually coming from your graphics driver. Which means that either (a) your GPU is too old and cannot support the shader, or (b) naga / wgpu corrupts the shader before handing it off to the graphics driver.

**Comment by dajmitonapake** [comment]
Ye, thats for sure, thanks
